name: codecov.io

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              gcc \
              acl \
              libacl1-dev \
              attr \
              libattr1-dev \
              libcap2-bin \
              libcap-dev \
              libonig-dev \
              liburing-dev

      - name: Generate coverage
        run: |
          make -j$(nproc) gcov check TEST_FLAGS="--sudo"
          gcov -abcfpu obj/*/*.o

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
